import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';

import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const enTranslation = {
  'Welcome to sahAIk': 'Welcome to sahAIk',
  'Teacher Login': 'Teacher Login',
  'Student Login': 'Student Login',
  'My Progress Report': 'My Progress Report',
  'Show Available Tests': 'Show Available Tests',
  'Take Test': 'Take Test',
  'Time Left': 'Time Left',
  'Test': 'Test',
  'Submit': 'Submit',
  'eduAssistant': 'eduAssistant',
  'sahAIkDesc1': "sahAIk is your AI-powered teaching companion for India's grassroots education system.",
  'sahAIkDesc2': 'Empowering teachers and students through inclusive, multilingual, and accessible tools.',
  'Multilingual Content': 'Multilingual Content',
  'Multilingual Content Desc': 'Generate and deliver lessons in local languages, making learning accessible for every child.',
  'Inclusive by Design': 'Inclusive by Design',
  'Inclusive by Design Desc': 'Designed for multi-grade classrooms and learners with disabilities, sahAIK adapts content to every student\'s needs.',
  'Teacher-first, Tech-smart': 'Teacher-first, Tech-smart',
  'Teacher-first, Tech-smart Desc': 'From lesson plans to assessments, sahAIK supports teachers with ready-to-use tools that work—even offline.',
  'No tests available for the selected class and subject.': 'No tests available for the selected class and subject.',
  'No test available': 'No test available',
  'Could not connect to the server. Please make sure the backend is running.': 'Could not connect to the server. Please make sure the backend is running.',
  'Loading suggestion...': 'Loading suggestion...',
  'Could not fetch suggestion.': 'Could not fetch suggestion.',
  'Welcome, Student!': 'Welcome, Student!',
  'Submit Answers': 'Submit Answers',
  'Your score': 'Your score',
  'Tips for your incorrect answers': 'Tips for your incorrect answers',
  'Back to Test List': 'Back to Test List',
  'Time is up! Your test has been submitted automatically.': 'Time is up! Your test has been submitted automatically.',
  'Select Language': 'Select Language',
  // Add more keys as needed
};

const resources = {
  en: { translation: enTranslation },
  hi: { translation: {
    'Welcome to sahAIk': 'सहAIK में आपका स्वागत है',
    'Teacher Login': 'शिक्षक लॉगिन',
    'Student Login': 'छात्र लॉगिन',
    'My Progress Report': 'मेरी प्रगति रिपोर्ट',
    'Show Available Tests': 'उपलब्ध परीक्षण दिखाएँ',
    'Take Test': 'परीक्षण दें',
    'Time Left': 'समय शेष',
    'Test': 'परीक्षण',
    'Submit': 'जमा करें',
    'eduAssistant': 'एडुअसिस्टेंट',
    'sahAIkDesc1': 'सहAIK भारत की जमीनी शिक्षा प्रणाली के लिए आपका एआई-संचालित शिक्षण साथी है।',
    'sahAIkDesc2': 'समावेशी, बहुभाषी और सुलभ उपकरणों के माध्यम से शिक्षकों और छात्रों को सशक्त बनाना।',
    'Multilingual Content': 'बहुभाषी सामग्री',
    'Multilingual Content Desc': 'स्थानीय भाषाओं में पाठ तैयार करें और वितरित करें, जिससे हर बच्चे के लिए शिक्षा सुलभ हो।',
    'Inclusive by Design': 'डिज़ाइन में समावेशी',
    'Inclusive by Design Desc': 'बहु-ग्रेड कक्षाओं और विकलांग छात्रों के लिए डिज़ाइन किया गया, सहAIK हर छात्र की ज़रूरत के अनुसार सामग्री अनुकूलित करता है।',
    'Teacher-first, Tech-smart': 'शिक्षक-प्रथम, तकनीक-प्रवीण',
    'Teacher-first, Tech-smart Desc': 'पाठ योजनाओं से लेकर मूल्यांकन तक, सहAIK शिक्षकों को तैयार उपकरणों के साथ समर्थन करता है जो ऑफ़लाइन भी काम करते हैं।',
    'No tests available for the selected class and subject.': 'चयनित कक्षा और विषय के लिए कोई परीक्षण उपलब्ध नहीं है।',
    'No test available': 'कोई परीक्षण उपलब्ध नहीं है',
    'Could not connect to the server. Please make sure the backend is running.': 'सर्वर से कनेक्ट नहीं हो सका। कृपया सुनिश्चित करें कि बैकएंड चल रहा है।',
    'Loading suggestion...': 'सुझाव लोड हो रहा है...',
    'Could not fetch suggestion.': 'सुझाव प्राप्त नहीं कर सके।',
    'Welcome, Student!': 'स्वागत है, छात्र!',
    'Submit Answers': 'उत्तर जमा करें',
    'Your score': 'आपका स्कोर',
    'Tips for your incorrect answers': 'आपके गलत उत्तरों के लिए सुझाव',
    'Back to Test List': 'परीक्षण सूची पर वापस जाएं',
    'Time is up! Your test has been submitted automatically.': 'समय समाप्त! आपका परीक्षण स्वचालित रूप से जमा कर दिया गया है।',
    'Select Language': 'भाषा चुनें',
    // Add more keys as needed
  } },
  bn: { translation: {
    'Welcome to sahAIk': 'sahAIk-এ আপনাকে স্বাগতম',
    'Teacher Login': 'শিক্ষক লগইন',
    'Student Login': 'ছাত্র লগইন',
    'My Progress Report': 'আমার অগ্রগতি প্রতিবেদন',
    'Show Available Tests': 'উপলব্ধ টেস্ট দেখান',
    'Take Test': 'পরীক্ষা দিন',
    'Time Left': 'সময় বাকি',
    'Test': 'পরীক্ষা',
    'Submit': 'জমা দিন',
    'eduAssistant': 'এডুঅ্যাসিস্ট্যান্ট',
    'sahAIkDesc1': 'sahAIk হল ভারতের গ্ৰামীণ শিক্ষার জন্য আপনার AI-চালিত শিক্ষক সহকারী।',
    'sahAIkDesc2': 'সমন্বিত, বহুভাষিক এবং অ্যাক্সেসযোগ্য টুলের মাধ্যমে শিক্ষক ও শিক্ষার্থীদের ক্ষমতায়ন।',
    'Multilingual Content': 'বহুভাষিক বিষয়বস্তু',
    'Multilingual Content Desc': 'স্থানীয় ভাষাওং মাঝে পাঠ তৈরি ও বিতরণ করুন, যাতে প্রতিটি শিশুর জন্য শিক্ষা সহজলভ্য হয়।',
    'Inclusive by Design': 'ডিজাইনে অন্তর্ভুক্তিমূলক',
    'Inclusive by Design Desc': 'বহু-গ্রেডের শ্রেণিকক্ষ এবং প্রতিবন্ধী শিক্ষার্থীদের জন্য ডিজাইন করা, sahAIk প্রতিটি শিক্ষার্থীর চাহিদা অনুযায়ী বিষয়বস্তু মানিয়ে নেয়।',
    'Teacher-first, Tech-smart': 'শিক্ষক-প্রথম, প্রযুক্তি-স্মার্ট',
    'Teacher-first, Tech-smart Desc': 'পাঠ পরিকল্পনা থেকে মূল্যায়ন পর্যন্ত, sahAIk শিক্ষকদের প্রস্তুত-ব্যবহারযোগ্য সরঞ্জাম দিয়ে সহায়তা করে যা অফলাইনে কাজ করে।',
    'No tests available for the selected class and subject.': 'নির্বাচিত শ্রেণি ও বিষয়ে কোনো টেস্ট নেই।',
    'No test available': 'কোনো টেস্ট নেই',
    'Could not connect to the server. Please make sure the backend is running.': 'সার্ভারের সাথে সংযোগ করা যায়নি। দয়া করে নিশ্চিত করুন যে ব্যাকএন্ড চল রহ્যુন ছে।',
    'Loading suggestion...': 'পরামর্শ লোড হচ্ছে...',
    'Could not fetch suggestion.': 'পরামর্শ আনতে পারিনি।',
    'Welcome, Student!': 'স্বাগত হোন, ছাত্র!',
    'Submit Answers': 'উত্তর জমা দিন',
    'Your score': 'আপনার স্কোর',
    'Tips for your incorrect answers': 'আপনার ভুল উত্তরের জন্য টিপস',
    'Back to Test List': 'পরীক্ষার তালিকায় ফিরে যান',
    'Time is up! Your test has been submitted automatically.': 'সময় শেষ! আপনার পরীক্ষা স্বয়ংক্রিয়ভাবে জমা দেওয়া হয়েছে।',
    'Select Language': 'ভাষা নির্বাচন করুন',
    // Add more keys as needed
  } },
  te: { translation: {
    'Welcome to sahAIk': 'sahAIk కు స్వాగతం',
    'Teacher Login': 'ఉపాధ్యాయ లాగిన్',
    'Student Login': 'విద్యార్థి లాగిన్',
    'My Progress Report': 'నా పురోగతి నివేదిక',
    'Show Available Tests': 'లభ్యమైన పరీక్షలను చూపించు',
    'Take Test': 'పరీక్ష రాయండి',
    'Time Left': 'మిగిలిన సమయం',
    'Test': 'పరీక్ష',
    'Submit': 'సమర్పించండి',
    'eduAssistant': 'ఎడ్యుఅసిస్టెంట్',
    'sahAIkDesc1': 'sahAIk భారతదేశ గ్రామీణ విద్యా వ్యవస్థ కోసం మీ AI ఆధారిత బోధన సహాయకుడు.',
    'sahAIkDesc2': 'సమావేశి, బహుభాషా మరియు సులభంగా ఉపయోగించదగిన సాధనాల ద్వారా ఉపాధ్యాయులు మరియు విద్యార్థులను శక్తివంతం చేయడం.',
    'Multilingual Content': 'బహుభాషా విషయవస్తువు',
    'Multilingual Content Desc': 'ప్రతి మక్కళిగె శిక్షణవన్ను సులభగೊళిసలు స్థళీయ భాషెగళల్లో పాఠగళన్ను రూపొందించండి మరియు అందించండి.',
    'Inclusive by Design': 'డిజైన్ ద్వారా సమావేశం',
    'Inclusive by Design Desc': 'బహుళ తరగతుల కోసం మరియు వికలాంగులైన విద్యార్థుల కోసం రూపొందించబడింది, sahAIk ప్రతి విద్యార్థి అవసరాలకు అనుగుణంగా విషయవన్ని అనుకూలీకరిస్తుంది.',
    'Teacher-first, Tech-smart': 'ఉపాధ్యాయ-ముందు, సాంకేతిక-స్మార్ట్',
    'Teacher-first, Tech-smart Desc': 'పాఠ్య ప్రణాళికల నుండి మూల్యాంకనాల వరకు, sahAIk ఉపాధ్యాయులను సిద్ధంగా ఉన్న సాధనాలతో మద్దతు ఇస్తుంది, అవి ఆఫ్‌లైన్‌లో కూడా పనిచేస్తాయి.',
    'No tests available for the selected class and subject.': 'ఎంచుకున్న తరగతి మరియు విషయానికి పరీక్షలు లభించవు.',
    'No test available': 'పరీక్షలు లేవు',
    'Could not connect to the server. Please make sure the backend is running.': 'సర్వర్‌కు కనెక్ట్ కాలేకపోయింది. దయచేసి బ్యాక్‌ఎండ్ నడుస్తున్నదని నిర్ధారించండి.',
    'Loading suggestion...': 'సూచన లోడ్ అవుతోంది...',
    'Could not fetch suggestion.': 'సూచనను పొందలేకపోయాం.',
    'Welcome, Student!': 'స్వాగతం, విద్యార్థి!',
    'Submit Answers': 'సమాధానాలు సమర్పించండి',
    'Your score': 'మీ స్కోర్',
    'Tips for your incorrect answers': 'మీ తప్పు సమాధానాల కోసం సూచనలు',
    'Back to Test List': 'పరీక్షల జాబితాకు తిరిగి వెళ్ళండి',
    'Time is up! Your test has been submitted automatically.': 'సమయం ముగిసింది! మీ పరీక్ష స్వయంచాలకంగా సమర్పించబడింది.',
    'Select Language': 'భాషను ఎంచుకోండి',
  } },
  mr: { translation: {
    'Welcome to sahAIk': 'sahAIk मध्ये आपले स्वागत आहे',
    'Teacher Login': 'शिक्षक लॉगिन',
    'Student Login': 'विद्यार्थी लॉगिन',
    'My Progress Report': 'माझी प्रगती अहवाल',
    'Show Available Tests': 'उपलब्ध चाचण्या दाखवा',
    'Take Test': 'चाचणी द्या',
    'Time Left': 'शिल्लक वेळ',
    'Test': 'चाचणी',
    'Submit': 'सबमिट करा',
    'eduAssistant': 'एड्युअसिस्टंट',
    'sahAIkDesc1': 'sahAIk ही भारताच्या ग्रामीण शिक्षण प्रणालीसाठी तुमची AI-संचालित शिक्षण सहायक आहे.',
    'sahAIkDesc2': 'समावेशक, बहुभाषिक आणि सुलभ साधनांद्वारे शिक्षक आणि विद्यार्थ्यांना सक्षम करणे.',
    'Multilingual Content': 'बहुभाषिक सामग्री',
    'Multilingual Content Desc': 'स्थानिक भाषांमध्ये धडे तयार करा आणि वितरित करा, प्रत्येक मुलासाठी शिक्षण सुलभ करा.',
    'Inclusive by Design': 'डिझाइननुसार समावेशक',
    'Inclusive by Design Desc': 'अनेक श्रेणींसाठी आणि दिव्यांग विद्यार्थ्यांसाठी डिझाइन केलेले, sahAIk प्रत्येक विद्यार्थ्याच्या गरजेनुसार सामग्री सानुकूलित करते.',
    'Teacher-first, Tech-smart': 'शिक्षक-प्रथम, तंत्रज्ञान-प्रवीण',
    'Teacher-first, Tech-smart Desc': 'पाठयोजना ते मूल्यमापन, sahAIk शिक्षकांना तयार साधनांसह समर्थन देते जे ऑफलाइन देखील कार्य करतात.',
    'No tests available for the selected class and subject.': 'निवडलेल्या वर्ग आणि विषयासाठी कोणतीही चाचणी उपलब्ध नाही.',
    'No test available': 'कोणतीही चाचणी उपलब्ध नाही',
    'Could not connect to the server. Please make sure the backend is running.': 'सर्व्हरशी कनेक्ट होऊ शकले नाही. कृपया बॅकएंड चालू आहे याची खात्री करा.',
    'Loading suggestion...': 'सूचना लोड होत आहे...',
    'Could not fetch suggestion.': 'सूचना मिळवू शकले नाही.',
    'Welcome, Student!': 'स्वागत आहे, विद्यार्थी!',
    'Submit Answers': 'उत्तर सबमिट करा',
    'Your score': 'तुमचा स्कोअर',
    'Tips for your incorrect answers': 'तुमच्या चुकीच्या उत्तरांसाठी टिप्स',
    'Back to Test List': 'चाचणी यादीवर परत जा',
    'Time is up! Your test has been submitted automatically.': 'वेळ संपली! तुमची चाचणी आपोआप सबमिट झाली आहे.',
    'Select Language': 'भाषा निवडा',
  } },
  ta: { translation: {
    'Welcome to sahAIk': 'sahAIk-க்கு வரவேற்கின்றோம்',
    'Teacher Login': 'ஆசிரியர் உள்நுழைவு',
    'Student Login': 'மாணவர் உள்நுழைவு',
    'My Progress Report': 'என் முன்னேற்ற அறிக்கை',
    'Show Available Tests': 'கிடைக்கும் தேர்வுகளை காண்பி',
    'Take Test': 'தேர்வு எழுதுங்கள்',
    'Time Left': 'மீதமுள்ள நேரம்',
    'Test': 'தேர்வு',
    'Submit': 'சமர்ப்பிக்கவும்',
    'eduAssistant': 'எட்யுஅசிஸ்டன்ட்',
    'sahAIkDesc1': 'sahAIk என்பது இந்தியாவின் கிராமப்புற கல்வி அமைப்பிற்கான உங்கள் AI இயக்கும் கற்றல் துணை.',
    'sahAIkDesc2': 'ஒற்றுமை, பன்மொழி மற்றும் அணுகக்கூடிய கருவிகள் மூலம் ஆசிரியர்களையும் மாணவர்களையும் அதிகாரப்படுத்துதல்.',
    'Multilingual Content': 'பன்மொழி உள்ளடக்கம்',
    'Multilingual Content Desc': 'உள்ளூர் மொழிகளில் பாடங்களை உருவாக்கி வழங்குங்கள், ஒவ்வொரு குழந்தைக்கும் கல்வியை அணுகக்கூடியதாக மாற்றுங்கள்.',
    'Inclusive by Design': 'வடிவமைப்பில் உள்ளடக்கம்',
    'Inclusive by Design Desc': 'பல வகுப்புகளுக்கும் மாற்றுத்திறனாளி மாணவர்களுக்கும் வடிவமைக்கப்பட்டுள்ளது, sahAIk ஒவ்வொரு மாணவரின் தேவைகளுக்கு ஏற்ப உள்ளடக்கத்தை தனிப்பயனாக்குகிறது.',
    'Teacher-first, Tech-smart': 'ஆசிரியர்-முதலில், தொழில்நுட்ப-புத்திசாலி',
    'Teacher-first, Tech-smart Desc': 'பாடத்திட்டங்கள் முதல் மதிப்பீடுகள் வரை, sahAIk ஆசிரியர்களை தயாராக உள்ள கருவிகளுடன் ஆதரிக்கிறது, அவை ஆஃப்லைனிலும் செயல்படும்.',
    'No tests available for the selected class and subject.': 'தேர்ந்தெடுக்கப்பட்ட வகுப்பு மற்றும் பாடத்திற்கான தேர்வுகள் இல்லை.',
    'No test available': 'தேர்வு இல்லை',
    'Could not connect to the server. Please make sure the backend is running.': 'சேவையகத்துடன் இணைக்க முடியவில்லை. பின்தள சேவை இயங்குகிறதா என்பதை உறுதிப்படுத்தவும்.',
    'Loading suggestion...': 'பரிந்துரை ஏற்றப்படுகிறது...',
    'Could not fetch suggestion.': 'பரிந்துரையை பெற முடியவில்லை.',
    'Welcome, Student!': 'வரவேற்கின்றோம், மாணவரே!',
    'Submit Answers': 'பதில்களை சமர்ப்பிக்கவும்',
    'Your score': 'உங்கள் மதிப்பெண்',
    'Tips for your incorrect answers': 'உங்கள் தவறான பதில்களுக்கு குறிப்புகள்',
    'Back to Test List': 'தேர்வு பட்டியலுக்கு திரும்பவும்',
    'Time is up! Your test has been submitted automatically.': 'நேரம் முடிந்தது! உங்கள் தேர்வு தானாகவே சமர்ப்பிக்கப்பட்டது.',
    'Select Language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
  } },
  gu: { translation: {
    'Welcome to sahAIk': 'sahAIk માં આપનું સ્વાગત છે',
    'Teacher Login': 'શિક્ષક લોગિન',
    'Student Login': 'વિદ્યાર્થી લોગિન',
    'My Progress Report': 'મારી પ્રગતિ રિપોર્ટ',
    'Show Available Tests': 'ઉપલબ્ધ પરીક્ષાઓ બતાવો',
    'Take Test': 'પરીક્ષા આપો',
    'Time Left': 'બાકી સમય',
    'Test': 'પરીક્ષા',
    'Submit': 'સબમિટ કરો',
    'eduAssistant': 'એડ્યુઅસિસ્ટન્ટ',
    'sahAIkDesc1': 'sahAIk એ ભારતની ગ્રામ્ય શિક્ષણ વ્યવસ્થામાં તમારો AI આધારિત શિક્ષણ સહાયક છે.',
    'sahAIkDesc2': 'સમાવિષ્ટ, બહુભાષી અને સુલભ સાધનો દ્વારા શિક્ષકો અને વિદ્યાર્થીઓને સશક્ત બનાવવું.',
    'Multilingual Content': 'બહુભાષી સામગ્રી',
    'Multilingual Content Desc': 'સ્થાનિક ભાષાઓમાં પાઠો બનાવો અને પહોંચાડો, દરેક બાળક માટે શિક્ષણને સુલભ બનાવો.',
    'Inclusive by Design': 'ડિઝાઇન દ્વારા સમાવેશ',
    'Inclusive by Design Desc': 'ઘણા વર્ગો અને દિવ્યાંગ વિદ્યાર્થીઓ માટે ડિઝાઇન કરેલું, sahAIk દરેક વિદ્યાર્થીની જરૂરિયાત મુજબ સામગ્રીને કસ્ટમાઇઝ કરે છે.',
    'Teacher-first, Tech-smart': 'શિક્ષક-પ્રથમ, ટેક-સ્માર્ટ',
    'Teacher-first, Tech-smart Desc': 'પાઠય યોજના થી મૂલ્યાંકન સુધી, sahAIk શિક્ષકોને તૈયાર સાધનો સાથે સપોર્ટ કરે છે, જે ઑફલાઇન પણ કામ કરે છે.',
    'No tests available for the selected class and subject.': 'પસંદ કરેલ વર્ગ અને વિષય માટે કોઈ પરીક્ષા ઉપલબ્ધ નથી.',
    'No test available': 'કોઈ પરીક્ષા ઉપલબ્ધ નથી',
    'Could not connect to the server. Please make sure the backend is running.': 'સર્વર સાથે કનેક્ટ કરી શક્યા નથી. કૃપા કરીને ખાતરી કરો કે બેકએન્ડ ચાલી રહ્યું છે.',
    'Loading suggestion...': 'સૂચન લોડ થઈ રહ્યું છે...',
    'Could not fetch suggestion.': 'સૂચન મેળવી શક્યા નથી.',
    'Welcome, Student!': 'સ્વાગત છે, વિદ્યાર્થી!',
    'Submit Answers': 'જવાબો સબમિટ કરો',
    'Your score': 'તમારો સ્કોર',
    'Tips for your incorrect answers': 'તમારા ખોટા જવાબો માટે સૂચનો',
    'Back to Test List': 'પરીક્ષા યાદી પર પાછા જાઓ',
    'Time is up! Your test has been submitted automatically.': 'સમય પૂરો થયો! તમારી પરીક્ષા આપમેળે સબમિટ થઈ ગઈ છે.',
    'Select Language': 'ભાષા પસંદ કરો',
  } },
  kn: { translation: {
    'Welcome to sahAIk': 'sahAIk ಗೆ ಸ್ವಾಗತ',
    'Teacher Login': 'ಶಿಕ್ಷಕ ಲಾಗಿನ್',
    'Student Login': 'ವಿದ್ಯಾರ್ಥಿ ಲಾಗಿನ್',
    'My Progress Report': 'ನನ್ನ ಪ್ರಗತಿ ವರದಿ',
    'Show Available Tests': 'ಲಭ್ಯವಿರುವ ಪರೀಕ್ಷೆಗಳನ್ನು ತೋರಿಸಿ',
    'Take Test': 'ಪರೀಕ್ಷೆ ಬರೆಯಿರಿ',
    'Time Left': 'ಉಳಿದ ಸಮಯ',
    'Test': 'ಪರೀಕ್ಷೆ',
    'Submit': 'ಸಲ್ಲಿಸು',
    'eduAssistant': 'ಎಡ್ಯುಅಸಿಸ್ಟೆಂಟ್',
    'sahAIkDesc1': 'sahAIk ಭಾರತ ಗ್ರಾಮೀಣ ಶಿಕ್ಷಣ ವ್ಯವಸ್ಥೆಗೆ ನಿಮ್ಮ AI ಚಾಲಿತ ಬೋಧನಾ ಸಹಾಯಕ.',
    'sahAIkDesc2': 'ಸಮಾವೇಶಿ, ಬಹುಭಾಷಾ ಮತ್ತು ಸುಲಭ ಸಾಧನಗಳ ಮೂಲಕ ಶಿಕ್ಷಕರನ್ನು ಮತ್ತು ವಿದ್ಯಾರ್ಥಿಗಳನ್ನು ಶಕ್ತಿಶಾಲಿಗಳನ್ನಾಗಿಸುವುದು.',
    'Multilingual Content': 'ಬಹುಭಾಷಾ ವಿಷಯ',
    'Multilingual Content Desc': 'ಪ್ರತಿ ಮಕ್ಕಳಿಗೆ ಶಿಕ್ಷಣವನ್ನು ಸುಲಭಗೊಳಿಸಲು ಸ್ಥಳೀಯ ಭಾಷೆಗಳಲ್ಲಿ ಪಾಠಗಳನ್ನು ರಚಿಸಿ ಮತ್ತು ವಿತರಿಸಿ.',
    'Inclusive by Design': 'ವಿನ್ಯಾಸದಲ್ಲಿ ಸಮಾವೇಶ',
    'Inclusive by Design Desc': 'ಬಹು ತರಗತಿಗಳಿಗಾಗಿ ಮತ್ತು ಅಂಗವಿಕಲ ವಿದ್ಯಾರ್ಥಿಗಳಿಗಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ, sahAIk ಪ್ರತಿ ವಿದ್ಯಾರ್ಥಿಯ ಅಗತ್ಯಗಳಿಗೆ ಅನುಗುಣವಾಗಿ ವಿಷಯವನ್ನು ಕಸ್ಟಮೈಸ್ ಮಾಡುತ್ತದೆ.',
    'Teacher-first, Tech-smart': 'ಶಿಕ್ಷಕ-ಮೊದಲು, ಟೆಕ್-ಸ್ಮಾರ್ಟ್',
    'Teacher-first, Tech-smart Desc': 'ಪಾಠ ಯೋಜನೆಗಳಿಂದ ಮೌಲ್ಯಮಾಪನದವರೆಗೆ, sahAIk ಶಿಕ್ಷಕರನ್ನು ಸಿದ್ಧ ಸಾಧನಗಳೊಂದಿಗೆ ಬೆಂಬಲಿಸುತ್ತದೆ, ಅವು ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿಯೂ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತವೆ.',
    'No tests available for the selected class and subject.': 'ಆಯ್ದ ತರಗತಿ ಮತ್ತು ವಿಷಯಕ್ಕೆ ಯಾವುದೇ ಪರೀಕ್ಷೆಗಳು ಲಭ್ಯವಿಲ್ಲ.',
    'No test available': 'ಯಾವುದೇ ಪರೀಕ್ಷೆ ಲಭ್ಯವಿಲ್ಲ',
    'Could not connect to the server. Please make sure the backend is running.': 'ಸರ್ವರ್‌ಗೆ ಸಂಪರ್ಕ ಸಾಧಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಬ್ಯಾಕ್‌ಎಂಡ್ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತಿದೆಯೆಂದು ಖಚಿತಪಡಿಸಿ.',
    'Loading suggestion...': 'ಸೂಚನೆ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'Could not fetch suggestion.': 'ಸೂಚನೆಯನ್ನು ಪಡೆಯಲಾಗಲಿಲ್ಲ.',
    'Welcome, Student!': 'ಸ್ವಾಗತ, ವಿದ್ಯಾರ್ಥಿ!',
    'Submit Answers': 'ಉತ್ತರಗಳನ್ನು ಸಲ್ಲಿಸಿ',
    'Your score': 'ನಿಮ್ಮ ಅಂಕಗಳು',
    'Tips for your incorrect answers': 'ನಿಮ್ಮ ತಪ್ಪಾದ ಉತ್ತರಗಳಿಗೆ ಸಲಹೆಗಳು',
    'Back to Test List': 'ಪರೀಕ್ಷಾ ಪಟ್ಟಿಗೆ ಹಿಂತಿರುಗಿ',
    'Time is up! Your test has been submitted automatically.': 'ಸಮಯ ಮುಗಿದಿದೆ! ನಿಮ್ಮ ಪರೀಕ್ಷೆಯನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ.',
    'Select Language': 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
  } },
  ml: { translation: {
    'Welcome to sahAIk': 'sahAIk-ലേക്ക് സ്വാഗതം',
    'Teacher Login': 'അധ്യാപക ലോഗിൻ',
    'Student Login': 'വിദ്യാർത്ഥി ലോഗിൻ',
    'My Progress Report': 'എന്റെ പുരോഗതി റിപ്പോർട്ട്',
    'Show Available Tests': 'ലഭ്യമായ പരീക്ഷകൾ കാണിക്കുക',
    'Take Test': 'പരീക്ഷ എഴുതുക',
    'Time Left': 'മിഴിയുള്ള സമയം',
    'Test': 'പരീക്ഷ',
    'Submit': 'സമർപ്പിക്കുക',
    'eduAssistant': 'എഡ്യുഅസിസ്റ്റന്റ്',
    'sahAIkDesc1': 'sahAIk ഇന്ത്യയുടെ ഗ്രാമീണ വിദ്യാഭ്യാസ സംവിധാനത്തിനുള്ള നിങ്ങളുടെ AI അധിഷ്ഠിത അധ്യാപന സഹായി.',
    'sahAIkDesc2': 'സമാവേശി, ബഹുഭാഷാ, സുലഭമായ ഉപകരണങ്ങളിലൂടെ അധ്യാപകരെയും വിദ്യാർത്ഥികളെയും ശക്തിപ്പെടുത്തുന്നു.',
    'Multilingual Content': 'ബഹുഭാഷാ ഉള്ളടക്കം',
    'Multilingual Content Desc': 'പ്രത്യേക കുട്ടികൾക്കായി വിദ്യാഭ്യാസം എളുപ്പമാക്കാൻ പ്രാദേശിക ഭാഷകളിൽ പാഠങ്ങൾ സൃഷ്ടിക്കുകയും വിതരണം ചെയ്യുകയും ചെയ്യുക.',
    'Inclusive by Design': 'ഡിസൈൻ വഴി സമാവേശം',
    'Inclusive by Design Desc': 'പല ക്ലാസുകൾക്കും ഭിന്നശേഷിയുള്ള വിദ്യാർത്ഥികൾക്കും രൂപകൽപ്പന ചെയ്തിരിക്കുന്നു, sahAIk ഓരോ വിദ്യാർത്ഥിയുടെ ആവശ്യങ്ങൾക്കനുസരിച്ച് ഉള്ളടക്കം ഇഷ്ടാനുസൃതമാക്കുന്നു.',
    'Teacher-first, Tech-smart': 'അധ്യാപകൻ-ആദ്യ, ടെക്ക്-സ്മാർട്ട്',
    'Teacher-first, Tech-smart Desc': 'പാഠ്യപദ്ധതികളിൽ നിന്ന് മൂല്യനിർണയത്തിലേക്ക്, sahAIk അധ്യാപകരെ തയ്യാറായ ഉപകരണങ്ങളാൽ പിന്തുണയ്ക്കുന്നു, അവ ഓഫ്‌ലൈൻ പോലും പ്രവർത്തിക്കും.',
    'No tests available for the selected class and subject.': 'തിരഞ്ഞെടുത്ത ക്ലാസിനും വിഷയത്തിനും പരീക്ഷകൾ ലഭ്യമല്ല.',
    'No test available': 'പരീക്ഷ ലഭ്യമല്ല',
    'Could not connect to the server. Please make sure the backend is running.': 'സർവറുമായി ബന്ധപ്പെടാൻ കഴിഞ്ഞില്ല. ദയവായി ബാക്ക്‌എൻഡ് പ്രവർത്തിക്കുന്നുണ്ടെന്ന് ഉറപ്പാക്കുക.',
    'Loading suggestion...': 'പരാമർശം ലോഡ് ചെയ്യുന്നു...',
    'Could not fetch suggestion.': 'പരാമർശം ലഭ്യമാക്കാനായില്ല.',
    'Welcome, Student!': 'സ്വാഗതം, വിദ്യാർത്ഥി!',
    'Submit Answers': 'ഉത്തരങ്ങൾ സമർപ്പിക്കുക',
    'Your score': 'നിങ്ങളുടെ സ്കോർ',
    'Tips for your incorrect answers': 'നിങ്ങളുടെ തെറ്റായ ഉത്തരങ്ങൾക്ക് നിർദ്ദേശങ്ങൾ',
    'Back to Test List': 'പരീക്ഷാ പട്ടികയിലേക്ക് മടങ്ങുക',
    'Time is up! Your test has been submitted automatically.': 'സമയം കഴിഞ്ഞു! നിങ്ങളുടെ പരീക്ഷ സ്വയമേവ സമർപ്പിച്ചു.',
    'Select Language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
  } },
  or: { translation: {
    'Welcome to sahAIk': 'sahAIk କୁ ସ୍ୱାଗତ',
    'Teacher Login': 'ଶିକ୍ଷକ ଲଗଇନ୍',
    'Student Login': 'ଛାତ୍ର ଲଗଇନ୍',
    'My Progress Report': 'ମୋର ଅଗ୍ରଗତି ରିପୋର୍ଟ',
    'Show Available Tests': 'ଉପଲବ୍ଧ ପରୀକ୍ଷାଗୁଡିକ ଦେଖାନ୍ତୁ',
    'Take Test': 'ପରୀକ୍ଷା ଦିଅନ୍ତୁ',
    'Time Left': 'ଅବଶିଷ୍ଟ ସମୟ',
    'Test': 'ପରୀକ୍ଷା',
    'Submit': 'ଦାଖଲ କରନ୍ତୁ',
    'eduAssistant': 'ଏଡ୍ୟୁଅସିଷ୍ଟେଣ୍ଟ',
    'sahAIkDesc1': 'sahAIk ହେଉଛି ଭାରତର ଗ୍ରାମୀଣ ଶିକ୍ଷା ପ୍ରଣାଳୀ ପାଇଁ ଆପଣଙ୍କର AI ଚାଳିତ ଶିକ୍ଷା ସହାୟକ।',
    'sahAIkDesc2': 'ସମାବେଶୀ, ବହୁଭାଷା ଏବଂ ସୁଲଭ ଉପକରଣ ଦ୍ୱାରା ଶିକ୍ଷକ ଏବଂ ଛାତ୍ରଛାତ୍ରୀଙ୍କୁ ସଶକ୍ତ କରିବା।',
    'Multilingual Content': 'ବହୁଭାଷା ବିଷୟବସ୍ତୁ',
    'Multilingual Content Desc': 'ସ୍ଥାନୀୟ ଭାଷାରେ ପାଠ୍ୟସାମଗ୍ରୀ ତିଆରି କରନ୍ତୁ ଏବଂ ପ୍ରଦାନ କରନ୍ତୁ, ପ୍ରତ୍ୟେକ ଶିଶୁ ପାଇଁ ଶିକ୍ଷାକୁ ସୁଲଭ କରନ୍ତୁ।',
    'Inclusive by Design': 'ଡିଜାଇନ୍ ଦ୍ୱାରା ସମାବେଶ',
    'Inclusive by Design Desc': 'ଏହା ବହୁ ଶ୍ରେଣୀ ଏବଂ ଅସମର୍ଥ ଛାତ୍ରଛାତ୍ରୀଙ୍କ ପାଇଁ ଡିଜାଇନ୍ କରାଯାଇଛି, sahAIk ପ୍ରତ୍ୟେକ ଛାତ୍ରର ଆବଶ୍ୟକତା ଅନୁଯାୟୀ ବିଷୟବସ୍ତୁକୁ ଅନୁକୂଳ କରେ।',
    'Teacher-first, Tech-smart': 'ଶିକ୍ଷକ-ପ୍ରଥମ, ଟେକ୍-ସ୍ମାର୍ଟ',
    'Teacher-first, Tech-smart Desc': 'ପାଠ୍ୟଯୋଜନାରୁ ମୂଲ୍ୟାଙ୍କନ ପର୍ଯ୍ୟନ୍ତ, sahAIk ଶିକ୍ଷକମାନେ ସଜା ଉପକରଣ ସହିତ ସହଯୋଗ କରନ୍ତି, ଯାହା ଅଫ୍ଲାଇନ୍ ମଧ୍ୟରେ କାମ କରେ।',
    'No tests available for the selected class and subject.': 'ଚୟନିତ ଶ୍ରେଣୀ ଏବଂ ବିଷୟ ପାଇଁ କୌଣସି ପରୀକ୍ଷା ଉପଲବ୍ଧ ନାହିଁ।',
    'No test available': 'କୌଣସି ପରୀକ୍ଷା ଉପଲବ୍ଧ ନାହିଁ',
    'Could not connect to the server. Please make sure the backend is running.': 'ସର୍ଭର ସହିତ ସଂଯୋଗ କରିପାରିଲେ ନାହିଁ। ଦୟାକରି ବ୍ୟାକଏଣ୍ଡ ଚାଲୁଛି କି ନାହିଁ ଯାଞ୍ଚ କରନ୍ତୁ।',
    'Loading suggestion...': 'ସୁପାରିଶ ଲୋଡ୍ ହେଉଛି...',
    'Could not fetch suggestion.': 'ସୁପାରିଶ ଆଣିପାରିଲେ ନାହିଁ।',
    'Welcome, Student!': 'ସ୍ୱାଗତ, ଛାତ୍ର!',
    'Submit Answers': 'ଉତ୍ତର ଦାଖଲ କରନ୍ତୁ',
    'Your score': 'ଆପଣଙ୍କର ଅଙ୍କ',
    'Tips for your incorrect answers': 'ଆପଣଙ୍କର ଭୁଲ ଉତ୍ତର ପାଇଁ ସୁପାରିଶ',
    'Back to Test List': 'ପରୀକ୍ଷା ତାଲିକାକୁ ଫେରନ୍ତୁ',
    'Time is up! Your test has been submitted automatically.': 'ସମୟ ସମାପ୍ତ! ଆପଣଙ୍କର ପରୀକ୍ଷା ସ୍ୱୟଂଚାଳିତ ଭାବେ ଦାଖଲ ହୋଇଛି।',
    'Select Language': 'ଭାଷା ବାଛନ୍ତୁ',
  } },
  pa: { translation: {
    'Welcome to sahAIk': 'sahAIk ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ',
    'Teacher Login': 'ਅਧਿਆਪਕ ਲਾਗਇਨ',
    'Student Login': 'ਵਿਦਿਆਰਥੀ ਲਾਗਇਨ',
    'My Progress Report': 'ਮੇਰੀ ਤਰੱਕੀ ਰਿਪੋਰਟ',
    'Show Available Tests': 'ਉਪਲਬਧ ਟੈਸਟ ਵੇਖੋ',
    'Take Test': 'ਟੈਸਟ ਦਿਓ',
    'Time Left': 'ਬਾਕੀ ਸਮਾਂ',
    'Test': 'ਟੈਸਟ',
    'Submit': 'ਸਮਰਪਿਤ ਕਰੋ',
    'eduAssistant': 'ਐਡਯੂਅਸਿਸਟੈਂਟ',
    'sahAIkDesc1': 'sahAIk ਭਾਰਤ ਦੇ ਪਿੰਡਾਂ ਦੀ ਸਿੱਖਿਆ ਪ੍ਰਣਾਲੀ ਲਈ ਤੁਹਾਡਾ AI-ਚਲਿਤ ਸਿੱਖਿਆ ਸਹਾਇਕ ਹੈ।',
    'sahAIkDesc2': 'ਸਮਾਵੇਸ਼ੀ, ਬਹੁਭਾਸ਼ਾਈ ਅਤੇ ਆਸਾਨ ਟੂਲਾਂ ਰਾਹੀਂ ਅਧਿਆਪਕਾਂ ਅਤੇ ਵਿਦਿਆਰਥੀਆਂ ਨੂੰ ਸ਼ਕਤੀਸ਼ਾਲੀ ਬਣਾਉਣਾ।',
    'Multilingual Content': 'ਬਹੁਭਾਸ਼ਾਈ ਸਮੱਗਰੀ',
    'Multilingual Content Desc': 'ਸਥਾਨਕ ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ ਪਾਠ ਬਣਾਓ ਅਤੇ ਪਹੁੰਚਾਓ, ਹਰ ਬੱਚੇ ਲਈ ਸਿੱਖਿਆ ਆਸਾਨ ਬਣਾਓ।',
    'Inclusive by Design': 'ਡਿਜ਼ਾਈਨ ਰਾਹੀਂ ਸਮਾਵੇਸ਼ੀ',
    'Inclusive by Design Desc': 'ਕਈ ਕਲਾਸਾਂ ਅਤੇ ਵਿਅੰਗ ਵਿਦਿਆਰਥੀਆਂ ਲਈ ਡਿਜ਼ਾਈਨ ਕੀਤਾ ਗਿਆ, sahAIk ਹਰ ਵਿਦਿਆਰਥੀ ਦੀ ਲੋੜ ਮੁਤਾਬਕ ਸਮੱਗਰੀ ਨੂੰ ਅਨੁਕੂਲ ਕਰਦਾ ਹੈ।',
    'Teacher-first, Tech-smart': 'ਅਧਿਆਪਕ-ਪਹਿਲਾਂ, ਟੈਕ-ਸਮਾਰਟ',
    'Teacher-first, Tech-smart Desc': 'ਪਾਠ ਯੋਜਨਾਵਾਂ ਤੋਂ ਮੁਲਾਂਕਣ ਤੱਕ, sahAIk ਅਧਿਆਪਕਾਂ ਨੂੰ ਤਿਆਰ ਟੂਲਾਂ ਨਾਲ ਸਹਾਇਤਾ ਕਰਦਾ ਹੈ, ਜੋ ਆਫਲਾਈਨ ਵੀ ਕੰਮ ਕਰਦੇ ਹਨ।',
    'No tests available for the selected class and subject.': 'ਚੁਣੀ ਹੋਈ ਕਲਾਸ ਅਤੇ ਵਿਸ਼ੇ ਲਈ ਕੋਈ ਟੈਸਟ ਉਪਲਬਧ ਨਹੀਂ ਹੈ।',
    'No test available': 'ਕੋਈ ਟੈਸਟ ਉਪਲਬਧ ਨਹੀਂ',
    'Could not connect to the server. Please make sure the backend is running.': 'ਸਰਵਰ ਨਾਲ ਕਨੈਕਟ ਨਹੀਂ ਹੋ ਸਕਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਯਕੀਨੀ ਬਣਾਓ ਕਿ ਬੈਕਐਂਡ ਚੱਲ ਰਿਹਾ ਹੈ।',
    'Loading suggestion...': 'ਸੁਝਾਅ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    'Could not fetch suggestion.': 'ਸੁਝਾਅ ਪ੍ਰਾਪਤ ਨਹੀਂ ਹੋ ਸਕਿਆ।',
    'Welcome, Student!': 'ਸੁਆਗਤ ਹੈ, ਵਿਦਿਆਰਥੀ!',
    'Submit Answers': 'ਉੱਤਰ ਸਮਰਪਿਤ ਕਰੋ',
    'Your score': 'ਤੁਹਾਡਾ ਸਕੋਰ',
    'Tips for your incorrect answers': 'ਤੁਹਾਡੇ ਗਲਤ ਉੱਤਰਾਂ ਲਈ ਸੁਝਾਅ',
    'Back to Test List': 'ਟੈਸਟ ਲਿਸਟ ਤੇ ਵਾਪਸ ਜਾਓ',
    'Time is up! Your test has been submitted automatically.': 'ਸਮਾਂ ਖਤਮ! ਤੁਹਾਡਾ ਟੈਸਟ ਆਟੋਮੈਟਿਕਲੀ ਸਮਰਪਿਤ ਹੋ ਗਿਆ ਹੈ।',
    'Select Language': 'ਭਾਸ਼ਾ ਚੁਣੋ',
  } },
  as: { translation: {
    'Welcome to sahAIk': 'sahAIk-ত আপোনালোকক স্বাগতম',
    'Teacher Login': 'শিক্ষক লগইন',
    'Student Login': 'ছাত্ৰ-ছাত্ৰী লগইন',
    'My Progress Report': 'মোৰ অগ্ৰগতি প্ৰতিবেদন',
    'Show Available Tests': 'উপলব্ধ পৰীক্ষাসমূহ দেখুৱাওক',
    'Take Test': 'পৰীক্ষা দিয়ক',
    'Time Left': 'অৱশিষ্ট সময়',
    'Test': 'পৰীক্ষা',
    'Submit': 'জমা দিয়ক',
    'eduAssistant': 'এড্যুঅছিষ্টেণ্ট',
    'sahAIkDesc1': 'sahAIk হৈছে ভাৰতৰ গ্ৰাম্য শিক্ষা ব্যৱস্থাৰ বাবে আপোনাৰ AI-চালিত শিক্ষা সহায়ক।',
    'sahAIkDesc2': 'সমাৱেশী, বহুভাষিক আৰু সহজ উপকৰণৰ জৰিয়তে শিক্ষক আৰু ছাত্ৰ-ছাত্ৰীক শক্তিশালী কৰা।',
    'Multilingual Content': 'বহুভাষিক সামগ্ৰী',
    'Multilingual Content Desc': 'স্থানীয় ভাষাত পাঠ্যবস্তু তৈয়াৰ কৰক আৰু বিতৰণ কৰক, প্ৰতিটো শিশুৰ বাবে শিক্ষা সহজ কৰক।',
    'Inclusive by Design': 'ডিজাইন অনুসৰি সমাৱেশী',
    'Inclusive by Design Desc': 'বহু শ্ৰেণী আৰু অক্ষম ছাত্ৰ-ছাত্ৰীসকলৰ বাবে ডিজাইন কৰা, sahAIk প্ৰতিটো ছাত্ৰৰ প্ৰয়োজন অনুসৰি সামগ্ৰী কাষ্টমাইজ কৰে।',
    'Teacher-first, Tech-smart': 'শিক্ষক-প্ৰথম, টেক-স্মাৰ্ট',
    'Teacher-first, Tech-smart Desc': 'পাঠ্য পৰিকল্পনা পৰা মূল্যায়নলৈ, sahAIk শিক্ষকক সাজু উপকৰণৰ সহায়ত সহায় কৰে, যি অফলাইনতো কাম কৰে।',
    'No tests available for the selected class and subject.': 'নিৰ্বাচিত শ্ৰেণী আৰু বিষয়ৰ বাবে কোনো পৰীক্ষা উপলব্ধ নাই।',
    'No test available': 'কোনো পৰীক্ষা উপলব্ধ নাই',
    'Could not connect to the server. Please make sure the backend is running.': 'চাৰ্ভাৰৰ সৈতে সংযোগ স্থাপন কৰিব পৰা নগ\'ল। অনুগ্ৰহ কৰি নিশ্চিত কৰক যে বেকএণ্ড চলি আছে।',
    'Loading suggestion...': 'পৰামৰ্শ লোড হৈছে...',
    'Could not fetch suggestion.': 'পৰামৰ্শ আনি পোৱা নগ\'ল।',
    'Welcome, Student!': 'স্বাগতম, ছাত্ৰ-ছাত্ৰী!',
    'Submit Answers': 'উত্তৰ জমা দিয়ক',
    'Your score': 'আপোনাৰ নম্বৰ',
    'Tips for your incorrect answers': 'আপোনাৰ ভুল উত্তৰৰ বাবে পৰামৰ্শ',
    'Back to Test List': 'পৰীক্ষাৰ তালিকালৈ উভতি যাওক',
    'Time is up! Your test has been submitted automatically.': 'সময় শেষ! আপোনাৰ পৰীক্ষা স্বয়ংক্ৰিয়ভাৱে জমা দিয়া হৈছে।',
    'Select Language': 'ভাষা বাছনি কৰক',
  } },
  ur: { translation: {
    'Welcome to sahAIk': 'sahAIk میں خوش آمدید',
    'Teacher Login': 'استاد لاگ ان',
    'Student Login': 'طالب علم لاگ ان',
    'My Progress Report': 'میری پیش رفت رپورٹ',
    'Show Available Tests': 'دستیاب ٹیسٹ دکھائیں',
    'Take Test': 'ٹیسٹ دیں',
    'Time Left': 'باقی وقت',
    'Test': 'ٹیسٹ',
    'Submit': 'جمع کریں',
    'eduAssistant': 'ایڈو اسسٹنٹ',
    'sahAIkDesc1': 'sahAIk بھارت کے دیہی تعلیمی نظام کے لیے آپ کا AI پر مبنی تدریسی معاون ہے۔',
    'sahAIkDesc2': 'شامل، کثیر لسانی اور قابل رسائی ٹولز کے ذریعے اساتذہ اور طلباء کو بااختیار بنانا۔',
    'Multilingual Content': 'کثیر لسانی مواد',
    'Multilingual Content Desc': 'مقامی زبانوں میں اسباق تیار کریں اور فراہم کریں، ہر بچے کے لیے تعلیم کو قابل رسائی بنائیں۔',
    'Inclusive by Design': 'ڈیزائن کے لحاظ سے شمولیت',
    'Inclusive by Design Desc': 'متعدد جماعتوں اور معذور طلباء کے لیے ڈیزائن کیا گیا، sahAIk ہر طالب علم کی ضروریات کے مطابق مواد کو حسب ضرورت بناتا ہے۔',
    'Teacher-first, Tech-smart': 'استاد-پہلا، ٹیک-سمارٹ',
    'Teacher-first, Tech-smart Desc': 'سبق کی منصوبہ بندی سے لے کر تشخیص تک، sahAIk اساتذہ کو تیار ٹولز کے ساتھ سپورٹ کرتا ہے جو آف لائن بھی کام کرتے ہیں۔',
    'No tests available for the selected class and subject.': 'منتخب کردہ جماعت اور مضمون کے لیے کوئی ٹیسٹ دستیاب نہیں ہے۔',
    'No test available': 'کوئی ٹیسٹ دستیاب نہیں',
    'Could not connect to the server. Please make sure the backend is running.': 'سرور سے کنکشن نہیں ہو سکا۔ براہ کرم یقینی بنائیں کہ بیک اینڈ چل رہا ہے۔',
    'Loading suggestion...': 'تجویز لوڈ ہو رہی ہے...',
    'Could not fetch suggestion.': 'تجویز حاصل نہیں کی جا سکی۔',
    'Welcome, Student!': 'خوش آمدید، طالب علم!',
    'Submit Answers': 'جوابات جمع کریں',
    'Your score': 'آپ کا اسکور',
    'Tips for your incorrect answers': 'آپ کے غلط جوابات کے لیے تجاویز',
    'Back to Test List': 'ٹیسٹ کی فہرست پر واپس جائیں',
    'Time is up! Your test has been submitted automatically.': 'وقت ختم! آپ کا ٹیسٹ خود بخود جمع کر دیا گیا ہے۔',
    'Select Language': 'زبان منتخب کریں',
  } },
  // Add more languages as needed
};

i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: 'en',
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false
    }
  });

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
